// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.huigod.namenode.rpc.model;

public interface AllocateDataNodesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.huigod.namenode.rpc.AllocateDataNodesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataNodes = 1;</code>
   * @return The dataNodes.
   */
  String getDataNodes();
  /**
   * <code>string dataNodes = 1;</code>
   * @return The bytes for dataNodes.
   */
  com.google.protobuf.ByteString
      getDataNodesBytes();
}
