// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.huigod.namenode.rpc.model;

public interface FetchEditsLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.huigod.namenode.rpc.FetchEditsLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string editsLog = 1;</code>
   * @return The editsLog.
   */
  String getEditsLog();
  /**
   * <code>string editsLog = 1;</code>
   * @return The bytes for editsLog.
   */
  com.google.protobuf.ByteString
      getEditsLogBytes();
}
