// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.huigod.namenode.rpc.model;

public interface GetDataNodeForFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.huigod.namenode.rpc.GetDataNodeForFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datanodeInfo = 1;</code>
   * @return The datanodeInfo.
   */
  String getDatanodeInfo();
  /**
   * <code>string datanodeInfo = 1;</code>
   * @return The bytes for datanodeInfo.
   */
  com.google.protobuf.ByteString
      getDatanodeInfoBytes();
}
