// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.huigod.namenode.rpc.model;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.huigod.namenode.rpc.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   * @return The ip.
   */
  String getIp();
  /**
   * <code>string ip = 1;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string home = 2;</code>
   * @return The home.
   */
  String getHome();
  /**
   * <code>string home = 2;</code>
   * @return The bytes for home.
   */
  com.google.protobuf.ByteString
      getHomeBytes();
}
