// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.huigod.namenode.rpc.model;

public final class NameNodeRpcModel {
  private NameNodeRpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huigod_namenode_rpc_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huigod_namenode_rpc_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huigod_namenode_rpc_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huigod_namenode_rpc_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huigod_namenode_rpc_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huigod_namenode_rpc_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_huigod_namenode_rpc_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_huigod_namenode_rpc_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026NameNodeRpcModel.proto\022\027com.huigod.nam" +
      "enode.rpc\"+\n\017RegisterRequest\022\n\n\002ip\030\001 \001(\t" +
      "\022\014\n\004home\030\002 \001(\t\"\"\n\020RegisterResponse\022\016\n\006st" +
      "atue\030\001 \001(\005\",\n\020HeartbeatRequest\022\n\n\002ip\030\001 \001" +
      "(\t\022\014\n\004home\030\002 \001(\t\"#\n\021HeartbeatResponse\022\016\n" +
      "\006statue\030\001 \001(\005B3\n\035com.huigod.namenode.rpc" +
      ".modelB\020NameNodeRpcModelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_huigod_namenode_rpc_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_huigod_namenode_rpc_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huigod_namenode_rpc_RegisterRequest_descriptor,
        new String[] { "Ip", "Home", });
    internal_static_com_huigod_namenode_rpc_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_huigod_namenode_rpc_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huigod_namenode_rpc_RegisterResponse_descriptor,
        new String[] { "Statue", });
    internal_static_com_huigod_namenode_rpc_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_huigod_namenode_rpc_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huigod_namenode_rpc_HeartbeatRequest_descriptor,
        new String[] { "Ip", "Home", });
    internal_static_com_huigod_namenode_rpc_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_huigod_namenode_rpc_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_huigod_namenode_rpc_HeartbeatResponse_descriptor,
        new String[] { "Statue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
