// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.huigod.namenode.rpc.model;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.huigod.namenode.rpc.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 statue = 1;</code>
   * @return The statue.
   */
  int getStatue();
}
