// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeServiceProtobuff.proto

package org.huigod.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036NameNodeServiceProtobuff.proto\032\036Regist" +
      "erRequestProtobuff.proto\032\037RegisterRespon" +
      "seProtobuff.proto\032\037HeartbeatRequestProto" +
      "buff.proto\032 HeartbeatResponseProtobuff.p" +
      "roto\032\033MkdirRequestProtobuff.proto\032\034Mkdir" +
      "ResponseProtobuff.proto2\315\001\n\025NameNodeServ" +
      "erService\022<\n\010register\022\027.RegisterRequestM" +
      "essage\032\027.RegisterRequestMessage\022@\n\theart" +
      "beat\022\030.HeartbeatRequestMessage\032\031.Heartbe" +
      "atResponseMessage\0224\n\005mkdir\022\024.MkdirReques" +
      "tMessage\032\025.MkdirResponseMessageB$\n\022org.h" +
      "uigod.serviceB\016NameNodeServerP\000P\001P\002P\003P\004P" +
      "\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.huigod.entity.RegisterRequest.getDescriptor(),
          org.huigod.entity.RegisterResponse.getDescriptor(),
          org.huigod.entity.HeartbeatRequest.getDescriptor(),
          org.huigod.entity.HeartbeatResponse.getDescriptor(),
          org.huigod.entity.MkdirRequest.getDescriptor(),
          org.huigod.entity.MkdirResponse.getDescriptor(),
        });
    org.huigod.entity.RegisterRequest.getDescriptor();
    org.huigod.entity.RegisterResponse.getDescriptor();
    org.huigod.entity.HeartbeatRequest.getDescriptor();
    org.huigod.entity.HeartbeatResponse.getDescriptor();
    org.huigod.entity.MkdirRequest.getDescriptor();
    org.huigod.entity.MkdirResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
